### ISSUE TITLE
Initial task list

### ISSUE THREAD

**Issue by gdude2002** [gear-cms/gear#1]
This is a list of stuff we need to do to get to a usable state which represents a good chunk of what we're trying to do here. This can be split off into separate issues and triaged as appropriate.

There's no ETA on this since we're all pretty busy.

- [ ] Plugins
    - [ ] Basic plugin loader
    - [ ] Design discussion (How should plugins interact, etc)
- [ ] Routes
    - [x] Basic route loader/manager
	- [x] Figure out route unloading with aiohttp (hopefully they don't break this..)
	- [ ] A set of default routes
		- [ ] First-time setup routes
		- [ ] Built-in control panel
- [ ] Storage
	- [ ] Database
		- [x] Threaded database decorator for SQLA
		- [ ] Figure out how on earth we can support reloading
		- [ ] Database migrations
		- [ ] Default schema
	- [ ] Files
		- [ ] Think about providing common filetype handlers
		- [ ] Think about where different types of files should go
		- [ ] Decide what should and shouldn't be in the database
		- [ ] Think about how to distribute file storage - maybe optional S3 support?
- [ ] Sync
	- [ ] Think about the best way to keep nodes up to date automatically
	- [ ] Decide whether to have one primary node for config, allow configuration on any node, or keep config on an entirely separate instance
	- [ ] Come up with more stuff for this item
- [ ] Templates
	- [ ] Think about the best way to store templates
	- [ ] Think about theming
	- [ ] Think about ways to allow plugins to modify templates
